- name: Deploy StackCheck Docker container
  hosts: production
  become: true
  tasks:
    - name: Install dependencies
      apt:
        name:
          - docker.io
          - ufw
        state: present
        update_cache: true

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Enable and start Docker
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Allow HTTP through UFW
      ufw:
        rule: allow
        port: '80'
        proto: tcp

    - name: Enable UFW 
      command: ufw --force enable
      ignore_errors: yes

    - name: Stop and remove old container
      command: docker rm -f stackcheck
      ignore_errors: true

    - name: Pull latest Docker image
      command: docker pull noopoo/stackcheck:latest

    - name: Run container
      command: docker run -d -p 80:80 --name stackcheck noopoo/stackcheck:latest
